name: hydrophonatics
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11
  - jupyter=1
  - notebook=6
  - pandas=2.1
  - numpy-base=1.26.2
  - matplotlib=3.8
  - numpy==1.24
  - resampy==0.4
  - tensorflow==2.15
  - tf_slim==1.1
  - six==1.16
  - soundfile==0.12
  - os
  - pandas==2.1
  - argparse 
  - librosa 
  - unittest2==1.1
  - yaml==0.2
  
  - pip:
      - pyspark==3.5
