name: hydrophonatics
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11
  - jupyter=1
  - notebook=6
  - pandas=2.1
  - numpy-base=1.26.2
  - matplotlib=3.8
  - pip:
      - librosa==0.10
      - pyspark==3.5
      - resampy==0.4
      - tensorflow==2.15
      - tf-slim==1.1
      - six==1.16
      - soundfile==0.12