name: hydrophonatics
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11
  - jupyter=1
  - notebook=6
  - pandas=2.1
  - numpy-base=1.26.2
  - matplotlib=3.8
  - pip:
      - pyspark==3.5
      - labelbox==3.59
      - labelbox[data]
      - ultralytics==8.1
      - requests==2.31
      - azure-keyvault-secrets==4.7
      - azure-identity==1.15
      - pylint==3.0
