name: vggish_environment
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11
  - jupyter=1
  - librosa=0.10
  - notebook=6
  - pandas=2.1
  - numpy-base=1.26.2
  - matplotlib=3.8
  - resampy=0.4
  - tensorflow=2.15
  - tf-slim=1.1
  - scikit-learn=1.3
  - scipy=1.11
  - six=1.16
  - soundfile=0.12
  - pip:
      - pyspark==3.5