name: vggish_run_environment
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.11
  - jupyter=1
  - notebook=6
  - pandas=2.1
  - numpy-base=1.26.2
  - matplotlib=3.8
  - pip:
      - pyspark==3.5
      - librosa==0.10
      - umap-learn
      - resampy==0.4
      - tensorflow==2.15
      - tf-slim==1.1
      - tqdm==4.66
      - six==1.16
      - scikit-learn
      - soundfile==0.12.1