name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hydrophonatics
          environment-file: environment.yml
          python-version: "3.11"
          auto-activate-base: false

      - name: Install additional dependencies
        run: |
          conda install -n hydrophonatics pylint pytest pytest-cov

      - name: Lint with pylint
        run: |
          conda run -n hydrophonatics pylint ./**/*.py

      - name: Test with pytest
        run: |
          conda run -n hydrophonatics pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
