name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - vggish/** #EKRC
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #All section below is EKRC
      - name: Check for submodule changes
        id: submodule_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.event.before }} ${{ github.sha }} | grep -q "vggish"; then
            echo "Changes detected in submodule"
            echo "::set-output name=submodule_changed::true"
          else
            echo "No changes detected in submodule"
            echo "::set-output name=submodule_changed::false"
          fi
      
      # All section below is ekrc
      - name: Set up Conda for specific path
        if: steps.submodule_changes.outputs.submodule_changed == 'true'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hydrophonatics
          environment-file: vggish/environment.yml
          python-version: "3.11"
          auto-activate-base: false

      - name: Set up Conda (Default)
        if: steps.submodule_changes.outputs.submodule_changed == 'false'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hydrophonatics
          environment-file: environment.yml
          python-version: "3.11"
          auto-activate-base: false

      - name: Install additional dependencies
        run: |
          conda install -n hydrophonatics pylint pytest pytest-cov

      - name: Lint with pylint
        run: |
          conda run -n hydrophonatics pylint ./**/*.py

      - name: Test with pytest
        run: |
          conda run -n hydrophonatics pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
